name: Build and Release zigzag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            zig_target: x86_64-linux-gnu
            archive_ext: tar.gz
            bin_ext: ""
          - os: macos-latest
            zig_target: x86_64-macos
            archive_ext: tar.gz
            bin_ext: ""
          - os: macos-latest
            zig_target: aarch64-macos
            archive_ext: tar.gz
            bin_ext: ""
          - os: windows-latest
            zig_target: x86_64-windows
            archive_ext: zip
            bin_ext: ".exe"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: Build zigzag
        run: |
          zig build --release=fast -Dtarget=${{ matrix.zig_target }}

      - name: Prepare release asset (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p dist
          cp zig-out/bin/zigzag${{ matrix.bin_ext }} dist/
          cd dist
          tar czvf ../zigzag-${{ github.ref_name }}-${{ matrix.zig_target }}.${{ matrix.archive_ext }} zigzag${{ matrix.bin_ext }}

      - name: Prepare release asset (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir dist
          copy zig-out\bin\zigzag${{ matrix.bin_ext }} dist\
          powershell Compress-Archive -Path dist\zigzag${{ matrix.bin_ext }} -DestinationPath zigzag-${{ github.ref_name }}-${{ matrix.zig_target }}.${{ matrix.archive_ext }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: zigzag ${{ github.ref_name }}
          files: |
            zigzag-${{ github.ref_name }}-${{ matrix.zig_target }}.${{ matrix.archive_ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
